# Generated by Django 4.2.6 on 2023-10-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("desc", models.TextField()),
                ("Year", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="movie",
        ),
    ]
