# Generated by Django 4.2.6 on 2023-10-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieapp", "0002_movielist_delete_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movielist",
            name="image",
            field=models.ImageField(default="dd", upload_to="pics"),
            preserve_default=False,
        ),
    ]
